name: ethereum_screener
services:
  ethereum_screener:
    build: .
    image: ethereum_screener:latest
    container_name: ethereum_screener
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    networks:
      - global-network
    restart: unless-stopped

networks:
  global-network:
    external: true
