services:
  ethereum_screener:
    image: cosmtrek/air
    container_name: ethereum_screener
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: sh -c "sleep 5 && air -c /app/air.toml"
    volumes:
      - ./:/app
    networks:
      - global-network
    restart: unless-stopped

networks:
  global-network:
    external: true
